-- ==============================================================================
-- 1. LIMPIEZA INICIAL (En orden inverso a las dependencias)
-- ==============================================================================

DROP TABLE IF EXISTS public.soporte_archivos CASCADE;
DROP TABLE IF EXISTS public.soporte_tickets CASCADE;
DROP TABLE IF EXISTS public.mensajes CASCADE;
DROP TABLE IF EXISTS public.conversaciones CASCADE;
DROP TABLE IF EXISTS public.firmas_boletas CASCADE;
DROP TABLE IF EXISTS public.calificaciones CASCADE;
DROP TABLE IF EXISTS public.asignaciones_docentes CASCADE;
DROP TABLE IF EXISTS public.parentescos CASCADE;
DROP TABLE IF EXISTS public.boletas_publicadas CASCADE;
DROP TABLE IF EXISTS public.alumnos CASCADE;
DROP TABLE IF EXISTS public.usuarios CASCADE;
DROP TABLE IF EXISTS public.periodos_evaluacion CASCADE;
DROP TABLE IF EXISTS public.materias CASCADE;
DROP TABLE IF EXISTS public.grupos CASCADE;
DROP TABLE IF EXISTS public.palabras_prohibidas CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;

-- ==============================================================================
-- 2. CREACIÓN DE TABLAS
-- ==============================================================================

CREATE TABLE public.roles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_rol character varying NOT NULL UNIQUE
);

CREATE TABLE public.palabras_prohibidas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  palabra character varying NOT NULL UNIQUE
);

CREATE TABLE public.grupos (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  grado integer NOT NULL CHECK (grado >= 1 AND grado <= 6),
  seccion character varying NOT NULL
);

CREATE TABLE public.materias (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre_materia character varying NOT NULL,
  es_general boolean DEFAULT false
);

CREATE TABLE public.periodos_evaluacion (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre character varying NOT NULL,
  mes_inicio integer NOT NULL CHECK (mes_inicio >= 1 AND mes_inicio <= 12),
  mes_fin integer NOT NULL CHECK (mes_fin >= 1 AND mes_fin <= 12)
);

CREATE TABLE public.usuarios (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  email character varying UNIQUE,
  nombre_completo character varying NOT NULL,
  rol_id integer REFERENCES public.roles(id),
  activo boolean DEFAULT false,
  creado_en timestamp without time zone DEFAULT now(),
  invitado_en timestamp without time zone DEFAULT now(),
  activado_en timestamp without time zone,
  auth_user_id uuid UNIQUE, -- Aquí vinculamos con auth.users de Supabase
  identificacion_docente character varying UNIQUE,
  codigo_registro character varying
);

CREATE TABLE public.alumnos (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  matricula character varying NOT NULL UNIQUE,
  nombre_completo character varying NOT NULL,
  grupo_id uuid REFERENCES public.grupos(id),
  fecha_nacimiento date NOT NULL,
  codigo_registro character varying
);

CREATE TABLE public.boletas_publicadas (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  periodo_id uuid NOT NULL UNIQUE REFERENCES public.periodos_evaluacion(id),
  publicada boolean DEFAULT false,
  publicada_por uuid REFERENCES public.usuarios(id),
  publicada_en timestamp without time zone DEFAULT now()
);

CREATE TABLE public.parentescos (
  padre_id uuid NOT NULL REFERENCES public.usuarios(id),
  alumno_id uuid NOT NULL REFERENCES public.alumnos(id),
  PRIMARY KEY (padre_id, alumno_id)
);

CREATE TABLE public.asignaciones_docentes (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  docente_id uuid NOT NULL REFERENCES public.usuarios(id),
  materia_id uuid NOT NULL REFERENCES public.materias(id),
  grupo_id uuid NOT NULL REFERENCES public.grupos(id)
);

CREATE TABLE public.calificaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  alumno_id uuid REFERENCES public.alumnos(id),
  materia_id uuid REFERENCES public.materias(id),
  nota numeric CHECK (nota >= 0 AND nota <= 10),
  comentario text,
  periodo_id uuid REFERENCES public.periodos_evaluacion(id),
  tarea character varying,
  evaluado_por uuid REFERENCES public.usuarios(id) -- Nueva columna de auditoría
);

CREATE TABLE public.firmas_boletas (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  alumno_id uuid REFERENCES public.alumnos(id),
  padre_id uuid REFERENCES public.usuarios(id),
  firmado_en timestamp without time zone DEFAULT now(),
  periodo_id uuid NOT NULL REFERENCES public.periodos_evaluacion(id)
);

CREATE TABLE public.conversaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  alumno_id uuid REFERENCES public.alumnos(id),
  padre_id uuid REFERENCES public.usuarios(id),
  docente_id uuid REFERENCES public.usuarios(id),
  creado_en timestamp without time zone DEFAULT now()
);

CREATE TABLE public.mensajes (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  conversacion_id uuid REFERENCES public.conversaciones(id),
  remitente_id uuid REFERENCES public.usuarios(id),
  contenido text NOT NULL,
  estado character varying DEFAULT 'enviado' CHECK (estado IN ('enviado', 'bloqueado', 'leido')),
  creado_en timestamp without time zone DEFAULT now()
);

CREATE TABLE public.soporte_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  ticket_codigo text NOT NULL UNIQUE,
  matricula text,
  estudiante_nombre text,
  fecha_nacimiento text,
  codigo_registro text,
  asunto text NOT NULL,
  descripcion text NOT NULL,
  estado text DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'En proceso', 'Resuelto')),
  creado_por uuid REFERENCES public.usuarios(id),
  creado_en timestamp without time zone DEFAULT now(),
  role integer NOT NULL REFERENCES public.roles(id)
);

CREATE TABLE public.soporte_archivos (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  ticket_id uuid REFERENCES public.soporte_tickets(id),
  archivo_url text NOT NULL,
  creado_en timestamp without time zone DEFAULT now()
);

-- ==============================================================================
-- 3. HABILITACIÓN DE SEGURIDAD (Row Level Security)
-- ==============================================================================

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.palabras_prohibidas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grupos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.periodos_evaluacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alumnos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boletas_publicadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parentescos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asignaciones_docentes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calificaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.firmas_boletas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mensajes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.soporte_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.soporte_archivos ENABLE ROW LEVEL SECURITY;

-- Nota: Las políticas (Policies) no se incluyen para permitir que el Backend (Service Role) 
-- y los administradores puedan configurar RLS a detalle posteriormente.
